# AI Trading System Configuration

# System Settings
system:
  name: "AI Trading System"
  version: "1.0.0"
  environment: "development"
  timezone: "Asia/Seoul"
  
# Database Configuration
database:
  main:
    driver: "postgresql"
    host: "localhost"
    port: 5432
    name: "ai_trading"
    pool_size: 20
    max_overflow: 30
    
  timeseries:
    driver: "timescaledb"
    host: "localhost"
    port: 5432
    name: "timescale_db"
    
  cache:
    driver: "redis"
    host: "localhost"
    port: 6379
    db: 0
    
# Trading Configuration
trading:
  markets:
    - name: "US_STOCKS"
      enabled: true
      session_hours:
        start: "09:30"
        end: "16:00"
        timezone: "America/New_York"
    - name: "KR_STOCKS"
      enabled: true
      session_hours:
        start: "09:00"
        end: "15:30"
        timezone: "Asia/Seoul"
    - name: "CRYPTO"
      enabled: true
      session_hours:
        start: "00:00"
        end: "23:59"
        timezone: "UTC"
        
  capital:
    initial: 120000000  # 1.2억원
    monthly_addition: 300000  # 30만원
    
  risk_management:
    max_risk_per_trade: 0.02
    max_daily_loss: 0.05
    max_drawdown: 0.15
    max_positions: 10
    position_sizing: "kelly_criterion"
    
  execution:
    order_type: "limit"
    timeout_seconds: 30
    slippage_tolerance: 0.001
    
# Data Collection
data:
  sources:
    price_data:
      - name: "yfinance"
        priority: 1
        rate_limit: 2000  # requests per hour
      - name: "alpaca"
        priority: 2
        rate_limit: 200
        
    news_data:
      - name: "news_api"
        priority: 1
        rate_limit: 1000
      - name: "alpha_vantage"
        priority: 2
        rate_limit: 500
        
    social_sentiment:
      - name: "twitter"
        priority: 1
        rate_limit: 300
        
  collection_intervals:
    price_data: "1m"  # 1 minute
    news_data: "5m"   # 5 minutes
    sentiment_data: "15m"  # 15 minutes
    
  storage:
    raw_data_retention: 365  # days
    processed_data_retention: 1095  # 3 years
    
# ML Models
models:
  technical_analysis:
    enabled: true
    model_type: "lstm"
    input_features:
      - "price"
      - "volume"
      - "technical_indicators"
    prediction_horizon: 5  # days
    retrain_frequency: "weekly"
    
  sentiment_analysis:
    enabled: true
    model_type: "transformer"
    sources:
      - "news"
      - "social_media"
      - "earnings_calls"
    retrain_frequency: "monthly"
    
  reinforcement_learning:
    enabled: true
    algorithm: "ppo"
    environment: "multi_asset_trading"
    training_frequency: "daily"
    
  ensemble:
    enabled: true
    voting_method: "weighted"
    weights:
      technical: 0.4
      sentiment: 0.3
      reinforcement: 0.3
      
# Strategies
strategies:
  momentum:
    enabled: true
    lookback_period: 20
    threshold: 0.02
    
  mean_reversion:
    enabled: true
    lookback_period: 50
    deviation_threshold: 2.0
    
  breakout:
    enabled: true
    volume_confirmation: true
    min_volume_ratio: 1.5
    
  news_driven:
    enabled: true
    sentiment_threshold: 0.7
    impact_decay: 24  # hours
    
# Backtesting
backtesting:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 120000000
  commission: 0.001  # 0.1%
  slippage: 0.0005   # 0.05%
  
# Monitoring & Alerts
monitoring:
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "avg_holding_period"
    
  alerts:
    daily_loss_threshold: 0.05
    drawdown_threshold: 0.10
    system_errors: true
    
  notifications:
    telegram:
      enabled: true
      daily_summary: true
      trade_alerts: true
      
    discord:
      enabled: false
      
    email:
      enabled: false
      
# Logging
logging:
  level: "INFO"
  format: "detailed"
  rotation: "daily"
  retention: 30  # days
  
# API Configuration
api:
  web_interface:
    host: "0.0.0.0"
    port: 8000
    cors_origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
      
  rate_limits:
    default: "100/minute"
    authenticated: "1000/minute"